import type { Keymap, Layer } from '../../types';

export interface KeymapGeneratorOptions {
  keyboard: string;
  layout?: string;
  includeComments?: boolean;
  via?: boolean;
}

export class KeymapGenerator {
  private keycodes: Map<string, string>;

  constructor() {
    this.keycodes = new Map([
      ['KC_ESC', 'KC_ESC'],
      ['KC_TAB', 'KC_TAB'],
      ['KC_ENT', 'KC_ENT'],
      ['KC_BSPC', 'KC_BSPC'],
      ['KC_ESC', 'KC_ESC'],
      ['KC_CAPS', 'KC_CAPS'],
      ['KC_LSFT', 'KC_LSFT'],
      ['KC_RSFT', 'KC_RSFT'],
      ['KC_LCTL', 'KC_LCTL'],
      ['KC_LALT', 'KC_LALT'],
      ['KC_LGUI', 'KC_LGUI'],
      ['KC_RCTL', 'KC_RCTL'],
      ['KC_RALT', 'KC_RALT'],
      ['KC_RGUI', 'KC_RGUI'],
      ['KC_SPC', 'KC_SPC'],
      ['KC_Q', 'KC_Q'],
      ['KC_W', 'KC_W'],
      ['KC_E', 'KC_E'],
      ['KC_R', 'KC_R'],
      ['KC_T', 'KC_T'],
      ['KC_Y', 'KC_Y'],
      ['KC_U', 'KC_U'],
      ['KC_I', 'KC_I'],
      ['KC_O', 'KC_O'],
      ['KC_P', 'KC_P'],
      ['KC_A', 'KC_A'],
      ['KC_S', 'KC_S'],
      ['KC_D', 'KC_D'],
      ['KC_F', 'KC_F'],
      ['KC_G', 'KC_G'],
      ['KC_H', 'KC_H'],
      ['KC_J', 'KC_J'],
      ['KC_K', 'KC_K'],
      ['KC_L', 'KC_L'],
      ['KC_Z', 'KC_Z'],
      ['KC_X', 'KC_X'],
      ['KC_C', 'KC_C'],
      ['KC_V', 'KC_V'],
      ['KC_B', 'KC_B'],
      ['KC_N', 'KC_N'],
      ['KC_M', 'KC_M'],
      ['KC_1', 'KC_1'],
      ['KC_2', 'KC_2'],
      ['KC_3', 'KC_3'],
      ['KC_4', 'KC_4'],
      ['KC_5', 'KC_5'],
      ['KC_6', 'KC_6'],
      ['KC_7', 'KC_7'],
      ['KC_8', 'KC_8'],
      ['KC_9', 'KC_9'],
      ['KC_0', 'KC_0'],
      ['KC_MINS', 'KC_MINS'],
      ['KC_EQL', 'KC_EQL'],
      ['KC_GRV', 'KC_GRV'],
      ['KC_SCLN', 'KC_SCLN'],
      ['KC_QUOT', 'KC_QUOT'],
      ['KC_COMM', 'KC_COMM'],
      ['KC_DOT', 'KC_DOT'],
      ['KC_SLSH', 'KC_SLSH'],
      ['KC_BSLS', 'KC_BSLS'],
      ['KC_LBRC', 'KC_LBRC'],
      ['KC_RBRC', 'KC_RBRC'],
      ['KC_NUHS', 'KC_NUHS'],
      ['KC_NUHS', 'KC_NUHS'],
      ['KC_LEFT', 'KC_LEFT'],
      ['KC_RIGHT', 'KC_RIGHT'],
      ['KC_UP', 'KC_UP'],
      ['KC_DOWN', 'KC_DOWN'],
      ['KC_PGUP', 'KC_PGUP'],
      ['KC_PGDN', 'KC_PGDN'],
      ['KC_HOME', 'KC_HOME'],
      ['KC_END', 'KC_END'],
      ['KC_INS', 'KC_INS'],
      ['KC_DEL', 'KC_DEL'],
      ['KC_F1', 'KC_F1'],
      ['KC_F2', 'KC_F2'],
      ['KC_F3', 'KC_F3'],
      ['KC_F4', 'KC_F4'],
      ['KC_F5', 'KC_F5'],
      ['KC_F6', 'KC_F6'],
      ['KC_F7', 'KC_F7'],
      ['KC_F8', 'KC_F8'],
      ['KC_F9', 'KC_F9'],
      ['KC_F10', 'KC_F10'],
      ['KC_F11', 'KC_F11'],
      ['KC_F12', 'KC_F12'],
      ['MO(1)', 'MO(1)'],
      ['MO(2)', 'MO(2)'],
      ['MO(3)', 'MO(3)'],
      ['MO(4)', 'MO(4)'],
      ['MO(5)', 'MO(5)'],
      ['TT(1)', 'TT(1)'],
      ['TT(2)', 'TT(2)'],
      ['TT(3)', 'TT(3)'],
      ['TT(4)', 'TT(4)'],
      ['TT(5)', 'TT(5)'],
      ['TG(1)', 'TG(1)'],
      ['TG(2)', 'TG(2)'],
      ['TG(3)', 'TG(3)'],
      ['TG(4)', 'TG(4)'],
      ['TG(5)', 'TG(5)'],
      ['KC_PSCR', 'KC_PSCR'],
      ['KC_SLCK', 'KC_SLCK'],
      ['KC_PAUS', 'KC_PAUS'],
      ['KC_NLCK', 'KC_NLCK'],
      ['KC_PENT', 'KC_PENT'],
      ['KC_PMNS', 'KC_PMNS'],
      ['KC_PPLS', 'KC_PPLS'],
      ['KC_PAST', 'KC_PAST'],
      ['KC_PSLS', 'KC_PSLS'],
      ['KC_P1', 'KC_P1'],
      ['KC_P2', 'KC_P2'],
      ['KC_P3', 'KC_P3'],
      ['KC_P4', 'KC_P4'],
      ['KC_P5', 'KC_P5'],
      ['KC_P6', 'KC_P6'],
      ['KC_P7', 'KC_P7'],
      ['KC_P8', 'KC_P8'],
      ['KC_P9', 'KC_P9'],
      ['KC_P0', 'KC_P0'],
      ['KC_PDOT', 'KC_PDOT'],
      ['KC_VOLD', 'KC_VOLD'],
      ['KC_VOLU', 'KC_VOLU'],
      ['KC_MUTE', 'KC_MUTE'],
      ['KC_MPRV', 'KC_MPRV'],
      ['KC_MNXT', 'KC_MNXT'],
      ['KC_MPLY', 'KC_MPLY'],
      ['TG', 'TG'],
      ['TO', 'TO'],
      ['MO', 'MO'],
      ['OSL', 'OSL'],
      ['LT', 'LT'],
      ['TT', 'TT'],
      ['LCAG', 'KC_LCAG'],
      ['RESET', 'RESET'],
      ['EEP_RST', 'EEP_RST'],
      ['KC_TRNS', 'KC_TRNS'],
      ['KC_NO', 'KC_NO'],
      ['_______', 'KC_TRNS'],
      ['XXXXXXX', 'KC_NO'],
    ]);
  }

  generate(keymap: Keymap, options: KeymapGeneratorOptions): string {
    const lines: string[] = [];
    const { keyboard, includeComments = true } = options;

    const isCrkbd = keyboard === 'crkbd' || keyboard === 'corne';

    lines.push('// Generated by Corne CLI');
    lines.push(`// Keyboard: ${keyboard}`);
    lines.push(`// Keymap: ${keymap.name}`);
    if (keymap.author) {
      lines.push(`// Author: ${keymap.author}`);
    }
    lines.push('');
    lines.push('#include QMK_KEYBOARD_H');
    lines.push('');

    if (isCrkbd) {
      lines.push('const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {');
      const layerCount = keymap.layers.length;
      for (let i = 0; i < layerCount; i++) {
        const layer = keymap.layers[i];
        if (includeComments) {
          lines.push(`    // Layer ${i}: ${layer.name}`);
        }
        lines.push(`    [${i}] = ${this.encodeLayerCrkbd(layer)},`);
      }
      lines.push('};');
    } else {
      lines.push('const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {');
      const layerCount = keymap.layers.length;
      for (let i = 0; i < layerCount; i++) {
        const layer = keymap.layers[i];
        if (includeComments) {
          lines.push(`  // Layer ${i}: ${layer.name}`);
        }
        lines.push(`  [${i}] = ${this.encodeLayer(layer)},`);
      }
      lines.push('};');
    }

    lines.push('');

    lines.push('const uint16_t PROGMEM fn_actions[] = {');

    const fnCount = this.countFnKeys(keymap);
    if (fnCount > 0) {
      lines.push('  // FN0 - action');
      lines.push('  ACTION_FUNCTION(0, 0, 0),');
    }

    lines.push('};');
    lines.push('');

    if (keymap.config?.oledConfig?.enabled) {
      lines.push(...this.generateOledConfig(keymap));
    }

    return lines.join('\n');
  }

  private encodeLayerCrkbd(layer: Layer): string {
    const keys = layer.keys;
    const rows: string[] = [];

    for (let r = 0; r < 3; r++) {
      const row = keys[r] || [];
      const left = row.slice(0, 6).map((kc) => this.normalizeKeycode(kc));
      const right = row.slice(6, 12).map((kc) => this.normalizeKeycode(kc));
      rows.push(left.join(', '));
      rows.push(right.join(', '));
    }

    const thumbLeft: string[] = [];
    const thumbRight: string[] = [];

    if (keys[3] && keys[3].length >= 6) {
      thumbLeft.push(...keys[3].slice(0, 3).map((kc) => this.normalizeKeycode(kc)));
      thumbRight.push(...keys[3].slice(3, 6).map((kc) => this.normalizeKeycode(kc)));
    } else {
      thumbLeft.push('KC_TRNS', 'KC_TRNS', 'KC_TRNS');
      thumbRight.push('KC_TRNS', 'KC_TRNS', 'KC_TRNS');
    }

    while (thumbLeft.length < 3) thumbLeft.unshift('KC_TRNS');
    while (thumbRight.length < 3) thumbRight.push('KC_TRNS');

    return `LAYOUT_split_3x6_3(
    //,-----------------------------------------------------.                    ,-----------------------------------------------------.
        ${rows[0]}  ,                         ${rows[1]},
    //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
        ${rows[2]}  ,                         ${rows[3]},
    //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
        ${rows[4]}  ,                         ${rows[5]},
    //|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
                                    ${thumbLeft.join(', ')}, ${thumbRight.join(', ')}
    //'--------------------------'  '--------------------------'
    )`;
  }

  private encodeLayer(layer: Layer): string {
    const keys = layer.keys;
    const rows = keys.map((row) => {
      const keyStrs = row.map((kc) => this.normalizeKeycode(kc));
      return `{ ${keyStrs.join(', ')} }`;
    });
    return `{\n    ${rows.join(',\n')}\n  }`;
  }

  private normalizeKeycode(code: string): string {
    const upper = code.toUpperCase();

    if (this.keycodes.has(upper)) {
      return upper;
    }

    if (code.startsWith('FN')) {
      const num = code.substring(2);
      if (/^\d+$/.test(num)) {
        return `F(${num})`;
      }
    }

    if (code.startsWith('( ') && code.endsWith(')')) {
      return code;
    }

    if (code === 'KC_TRNS' || code === '_______') {
      return 'KC_TRNS';
    }

    if (code === 'KC_NO' || code === 'XXXXXXX') {
      return 'KC_NO';
    }

    return 'KC_NO';
  }

  private countFnKeys(keymap: Keymap): number {
    let count = 0;
    for (const layer of keymap.layers) {
      for (const row of layer.keys) {
        for (const key of row) {
          if (key.startsWith('FN')) {
            count++;
          }
        }
      }
    }
    return count;
  }

  private *generateOledConfig(keymap: Keymap): Generator<string, void, unknown> {
    const oled = keymap.config?.oledConfig;
    if (!oled?.enabled) return;

    yield '';
    yield '// OLED configuration';
    yield '#ifdef OLED_ENABLE';
    yield '';

    if (oled.leftDisplay.type) {
      yield `// Left display: ${oled.leftDisplay.type}`;
    }
    if (oled.rightDisplay.type) {
      yield `// Right display: ${oled.rightDisplay.type}`;
    }

    yield '#endif';
  }
}

export const keymapGenerator = new KeymapGenerator();