// Layer-specific OLED animation system for QMK

export interface LayerAnimationConfig {
  enabled: boolean;
  enableTransitions: boolean;  // Smooth fade between layers
  transitionDuration: number;  // Transition time in ms (default: 200)
  layers: LayerDefinition[];
}

export interface LayerDefinition {
  id: number;                  // QMK layer number (0 = Base, 1 = Lower, 2 = Raise, etc.)
  name: string;                // Layer name (e.g., "Base", "Lower", "Raise", "Adjust")
  animation: {
    frames: Buffer[];
    frameDelay: number;        // Delay between frames in ms
  };
  indicator?: {
    text?: string;             // Optional text indicator
    position?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
  };
}

export interface LayerAnimationSet {
  layers: LayerDefinition[];
  config: LayerAnimationConfig;
}

export const DEFAULT_LAYER_NAMES = ['Base', 'Lower', 'Raise', 'Adjust', 'Function', 'NumPad'];

/**
 * Generate QMK code for layer-specific animations
 */
export class LayerAnimationGenerator {
  private config: LayerAnimationConfig;
  private width: number;
  private height: number;

  constructor(config: LayerAnimationConfig, width: number = 128, height: number = 32) {
    this.config = config;
    this.width = width;
    this.height = height;
  }

  /**
   * Generate complete QMK C code for layer animations
   */
  generateQMKCode(animationSet: LayerAnimationSet): string {
    const lines: string[] = [];

    // Header comments
    lines.push('// Layer-Specific OLED Animation System');
    lines.push('// Generated by corne-cli');
    lines.push('//');
    lines.push(`// Layers configured: ${animationSet.layers.length}`);
    lines.push(`// Transitions: ${this.config.enableTransitions ? 'enabled' : 'disabled'}`);
    if (this.config.enableTransitions) {
      lines.push(`// Transition duration: ${this.config.transitionDuration}ms`);
    }
    lines.push('');

    // Configuration constants
    lines.push(`#define LAYER_ANIMATION_ENABLED`);
    lines.push(`#define OLED_SIZE ${(this.width * this.height) / 8}`);
    lines.push(`#define LAYER_COUNT ${animationSet.layers.length}`);
    if (this.config.enableTransitions) {
      lines.push(`#define LAYER_TRANSITION_ENABLED`);
      lines.push(`#define LAYER_TRANSITION_DURATION ${this.config.transitionDuration}`);
    }
    lines.push('');

    // Layer IDs enum
    lines.push('// Layer definitions (should match your keymap layers)');
    lines.push('typedef enum {');
    animationSet.layers.forEach((layer, index) => {
      const comma = index < animationSet.layers.length - 1 ? ',' : '';
      lines.push(`    ${layer.name.toUpperCase()} = ${layer.id}${comma}`);
    });
    lines.push('} keyboard_layer_t;');
    lines.push('');

    // Generate animation data for each layer
    animationSet.layers.forEach((layer, _layerIndex) => {
      lines.push(`// === ${layer.name} Layer Animation ===`);
      lines.push('');

      // Generate frames for this layer
      const framesArray = this.generateAnimationFrames(
        layer.animation.frames,
        layer.animation.frameDelay,
        `${layer.name.toLowerCase()}_anim`
      );
      lines.push(framesArray);
      lines.push('');

      // Frame count constant
      lines.push(`#define ${layer.name.toUpperCase()}_FRAME_COUNT ${layer.animation.frames.length}`);
      lines.push(`#define ${layer.name.toUpperCase()}_FRAME_DELAY ${layer.animation.frameDelay}`);
      lines.push('');
    });

    // Layer animation lookup structure
    lines.push('// Layer animation lookup table');
    lines.push('typedef struct {');
    lines.push('    uint8_t layer_id;');
    lines.push('    const char *const *frames;');
    lines.push('    uint8_t frame_count;');
    lines.push('    uint16_t frame_delay;');
    lines.push('    const char *layer_name;');
    lines.push('} layer_animation_t;');
    lines.push('');

    lines.push('static const layer_animation_t PROGMEM layer_animations[] = {');
    animationSet.layers.forEach((layer, index) => {
      const comma = index < animationSet.layers.length - 1 ? ',' : '';
      lines.push(`    {${layer.id}, ${layer.name.toLowerCase()}_anim, ${layer.name.toUpperCase()}_FRAME_COUNT, ${layer.name.toUpperCase()}_FRAME_DELAY, "${layer.name}"}${comma}`);
    });
    lines.push('};');
    lines.push('');

    // Animation state variables
    lines.push('// Animation state');
    lines.push('static struct {');
    lines.push('    uint8_t current_layer;');
    lines.push('    uint8_t current_frame;');
    lines.push('    uint32_t anim_timer;');
    if (this.config.enableTransitions) {
      lines.push('    uint8_t transitioning;');
      lines.push('    uint32_t transition_timer;');
      lines.push('    uint8_t previous_layer;');
    }
    lines.push('} anim_state = {0};');
    lines.push('');

    // Helper function to get current animation
    lines.push('// Get animation for current layer');
    lines.push('static const layer_animation_t* get_layer_animation(uint8_t layer) {');
    lines.push('    for (uint8_t i = 0; i < LAYER_COUNT; i++) {');
    lines.push('        if (layer_animations[i].layer_id == layer) {');
    lines.push('            return &layer_animations[i];');
    lines.push('        }');
    lines.push('    }');
    lines.push('    return &layer_animations[0]; // Default to first layer');
    lines.push('}');
    lines.push('');

    // Main render function
    lines.push('// Render layer-specific animation');
    lines.push('void render_layer_animation(void) {');
    lines.push('    uint8_t active_layer = get_highest_layer(layer_state);');
    lines.push('    const layer_animation_t *anim = get_layer_animation(active_layer);');
    lines.push('');

    if (this.config.enableTransitions) {
      // With transitions
      lines.push('    // Handle layer change');
      lines.push('    if (active_layer != anim_state.current_layer) {');
      lines.push('        anim_state.previous_layer = anim_state.current_layer;');
      lines.push('        anim_state.current_layer = active_layer;');
      lines.push('        anim_state.transitioning = 1;');
      lines.push('        anim_state.transition_timer = timer_read32();');
      lines.push('        anim_state.current_frame = 0; // Reset frame for new layer');
      lines.push('    }');
      lines.push('');
      lines.push('    // Handle transition');
      lines.push('    if (anim_state.transitioning) {');
      lines.push('        uint32_t transition_elapsed = timer_elapsed32(anim_state.transition_timer);');
      lines.push('        if (transition_elapsed >= LAYER_TRANSITION_DURATION) {');
      lines.push('            anim_state.transitioning = 0;');
      lines.push('        }');
      lines.push('        // During transition, show new layer (fade effect handled by QMK)');
      lines.push('    }');
      lines.push('');
    } else {
      // Without transitions
      lines.push('    // Handle layer change');
      lines.push('    if (active_layer != anim_state.current_layer) {');
      lines.push('        anim_state.current_layer = active_layer;');
      lines.push('        anim_state.current_frame = 0; // Reset frame for new layer');
      lines.push('    }');
      lines.push('');
    }

    // Frame animation logic
    lines.push('    // Animate current layer');
    lines.push('    if (timer_elapsed32(anim_state.anim_timer) > anim->frame_delay) {');
    lines.push('        anim_state.anim_timer = timer_read32();');
    lines.push('        oled_write_raw_P(anim->frames[anim_state.current_frame], OLED_SIZE);');
    lines.push('        anim_state.current_frame = (anim_state.current_frame + 1) % anim->frame_count;');
    lines.push('    }');
    lines.push('}');
    lines.push('');

    // Layer indicator overlay (optional)
    lines.push('// Optional: Render layer name indicator');
    lines.push('void render_layer_indicator(void) {');
    lines.push('    const layer_animation_t *anim = get_layer_animation(anim_state.current_layer);');
    lines.push('    oled_set_cursor(0, 0);');
    lines.push('    oled_write_P(PSTR("Layer: "), false);');
    lines.push('    oled_write(anim->layer_name, false);');
    lines.push('}');
    lines.push('');

    // Usage instructions
    lines.push('// === USAGE INSTRUCTIONS ===');
    lines.push('// Add to your oled_task_user() function:');
    lines.push('//');
    lines.push('// bool oled_task_user(void) {');
    lines.push('//     if (is_keyboard_master()) {');
    lines.push('//         render_layer_animation();');
    lines.push('//         // Optional: render_layer_indicator();');
    lines.push('//     } else {');
    lines.push('//         // Right display content');
    lines.push('//     }');
    lines.push('//     return false;');
    lines.push('// }');

    return lines.join('\n');
  }

  /**
   * Generate animation frames as C array
   */
  private generateAnimationFrames(frames: Buffer[], frameDelay: number, name: string): string {
    const lines: string[] = [];
    const bytesPerLine = 16;
    const frameSize = this.width * this.height / 8;

    lines.push(`// ${name} - ${frames.length} frames @ ${frameDelay}ms`);
    lines.push(`static const char PROGMEM ${name}[][OLED_SIZE] = {`);

    frames.forEach((frameBuffer, frameIndex) => {
      lines.push(`    // Frame ${frameIndex}`);
      lines.push('    {');

      const bytes: number[] = Array.from(frameBuffer.slice(0, frameSize));
      
      for (let i = 0; i < bytes.length; i += bytesPerLine) {
        const chunk = bytes.slice(i, i + bytesPerLine);
        const formatted = chunk.map(b => `0x${b.toString(16).padStart(2, '0')}`).join(', ');
        const isLast = i + bytesPerLine >= bytes.length;
        lines.push(`        ${formatted}${isLast ? '' : ','}`);
      }

      const isLastFrame = frameIndex === frames.length - 1;
      lines.push(`    }${isLastFrame ? '' : ','}`);
    });

    lines.push('};');
    
    return lines.join('\n');
  }

  /**
   * Validate layer animation configuration
   */
  validateConfig(animationSet: LayerAnimationSet): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    // Check if at least one layer is defined
    if (!animationSet.layers || animationSet.layers.length === 0) {
      errors.push('No layers defined in animation set');
    }

    // Check for duplicate layer IDs
    const layerIds = animationSet.layers.map(l => l.id);
    const duplicates = layerIds.filter((id, index) => layerIds.indexOf(id) !== index);
    if (duplicates.length > 0) {
      errors.push(`Duplicate layer IDs found: ${duplicates.join(', ')}`);
    }

    // Validate each layer
    animationSet.layers.forEach((layer, index) => {
      if (!layer.name || layer.name.trim() === '') {
        errors.push(`Layer ${index}: name is required`);
      }

      if (layer.id < 0 || layer.id > 31) {
        errors.push(`Layer ${index} (${layer.name}): ID must be between 0 and 31`);
      }

      if (!layer.animation || !layer.animation.frames || layer.animation.frames.length === 0) {
        errors.push(`Layer ${index} (${layer.name}): no animation frames provided`);
      }

      if (layer.animation && layer.animation.frameDelay < 10) {
        errors.push(`Layer ${index} (${layer.name}): frame delay too low (minimum 10ms recommended)`);
      }
    });

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  /**
   * Generate example configuration
   */
  static generateExample(): LayerAnimationConfig {
    return {
      enabled: true,
      enableTransitions: true,
      transitionDuration: 200,
      layers: [
        {
          id: 0,
          name: 'Base',
          animation: {
            frames: [],
            frameDelay: 100,
          },
        },
        {
          id: 1,
          name: 'Lower',
          animation: {
            frames: [],
            frameDelay: 80,
          },
          indicator: {
            text: 'SYM',
            position: 'top-right',
          },
        },
        {
          id: 2,
          name: 'Raise',
          animation: {
            frames: [],
            frameDelay: 80,
          },
          indicator: {
            text: 'NUM',
            position: 'top-right',
          },
        },
      ],
    };
  }
}

export const DEFAULT_LAYER_CONFIG: LayerAnimationConfig = {
  enabled: true,
  enableTransitions: true,
  transitionDuration: 200,
  layers: [],
};
