// WPM (Words Per Minute) based animation system for QMK OLED displays

export interface WPMConfig {
  enabled: boolean;
  idleThreshold: number;      // WPM below this triggers idle animation (default: 20)
  typingThreshold: number;    // WPM above this triggers fast typing animation (default: 60)
  updateInterval: number;     // How often to update WPM display in ms (default: 100)
  showCounter: boolean;       // Display WPM number on screen
  counterPosition?: 'top' | 'bottom' | 'left' | 'right';
}

export interface WPMAnimationSet {
  idle: {
    frames: Buffer[];
    frameDelay: number;
  };
  typing: {
    frames: Buffer[];
    frameDelay: number;
  };
  fast?: {
    frames: Buffer[];
    frameDelay: number;
  };
}

/**
 * Generate QMK code for WPM-based animations
 */
export class WPMAnimationGenerator {
  private config: WPMConfig;
  private width: number;
  private height: number;

  constructor(config: WPMConfig, width: number = 128, height: number = 32) {
    this.config = config;
    this.width = width;
    this.height = height;
  }

  /**
   * Generate complete QMK C code for WPM animations
   */
  generateQMKCode(animationSet: WPMAnimationSet, animationName: string = 'wpm_animation'): string {
    const lines: string[] = [];

    // Header comments
    lines.push('// WPM-Based OLED Animation System');
    lines.push('// Generated by corne-cli');
    lines.push('//');
    lines.push(`// Idle threshold: ${this.config.idleThreshold} WPM`);
    lines.push(`// Typing threshold: ${this.config.typingThreshold} WPM`);
    lines.push(`// Update interval: ${this.config.updateInterval}ms`);
    lines.push('');

    // Configuration constants
    lines.push(`#define WPM_IDLE_THRESHOLD ${this.config.idleThreshold}`);
    lines.push(`#define WPM_TYPING_THRESHOLD ${this.config.typingThreshold}`);
    lines.push(`#define WPM_UPDATE_INTERVAL ${this.config.updateInterval}`);
    lines.push(`#define OLED_SIZE ${(this.width * this.height) / 8}`);
    lines.push('');

    // Animation states enum
    lines.push('typedef enum {');
    lines.push('    ANIM_IDLE,');
    lines.push('    ANIM_TYPING,');
    if (animationSet.fast) {
      lines.push('    ANIM_FAST');
    }
    lines.push('} anim_state_t;');
    lines.push('');

    // Generate idle animation
    lines.push(this.generateAnimationFrames(
      animationSet.idle.frames,
      animationSet.idle.frameDelay,
      'idle_animation'
    ));
    lines.push('');

    // Generate typing animation
    lines.push(this.generateAnimationFrames(
      animationSet.typing.frames,
      animationSet.typing.frameDelay,
      'typing_animation'
    ));
    lines.push('');

    // Generate fast typing animation if provided
    if (animationSet.fast) {
      lines.push(this.generateAnimationFrames(
        animationSet.fast.frames,
        animationSet.fast.frameDelay,
        'fast_animation'
      ));
      lines.push('');
    }

    // Animation frame counts
    lines.push(`#define IDLE_FRAME_COUNT ${animationSet.idle.frames.length}`);
    lines.push(`#define TYPING_FRAME_COUNT ${animationSet.typing.frames.length}`);
    if (animationSet.fast) {
      lines.push(`#define FAST_FRAME_COUNT ${animationSet.fast.frames.length}`);
    }
    lines.push('');

    // Frame durations
    lines.push(`#define IDLE_FRAME_DURATION ${animationSet.idle.frameDelay}`);
    lines.push(`#define TYPING_FRAME_DURATION ${animationSet.typing.frameDelay}`);
    if (animationSet.fast) {
      lines.push(`#define FAST_FRAME_DURATION ${animationSet.fast.frameDelay}`);
    }
    lines.push('');

    // Animation state management
    lines.push(this.generateAnimationStateCode(!!animationSet.fast));
    lines.push('');

    // WPM display function
    if (this.config.showCounter) {
      lines.push(this.generateWPMDisplayCode());
      lines.push('');
    }

    // Main render function
    lines.push(this.generateRenderFunction(!!animationSet.fast));
    lines.push('');

    // Usage instructions
    lines.push('// ========================================');
    lines.push('// Usage in keymap.c:');
    lines.push('// ========================================');
    lines.push('//');
    lines.push('// 1. Enable WPM in rules.mk:');
    lines.push('//    WPM_ENABLE = yes');
    lines.push('//');
    lines.push('// 2. In oled_task_user(), call:');
    lines.push('//    render_wpm_animation(is_keyboard_master());');
    lines.push('//');
    lines.push('// 3. Optional: Display WPM on the other OLED:');
    lines.push('//    if (!is_keyboard_master()) {');
    lines.push('//        render_wpm_counter();');
    lines.push('//    }');

    return lines.join('\n');
  }

  /**
   * Generate animation frame data
   */
  private generateAnimationFrames(frames: Buffer[], frameDelay: number, animationName: string): string {
    const lines: string[] = [];
    const _frameSize = (this.width * this.height) / 8;

    lines.push(`// ${animationName} - ${frames.length} frames @ ${frameDelay}ms`);
    lines.push(`static const char PROGMEM ${animationName}[${frames.length}][OLED_SIZE] = {`);

    frames.forEach((frameBuffer, frameIndex) => {
      const bytes: number[] = [];

      // Convert frame to QMK format (vertical byte format)
      for (let page = 0; page < this.height / 8; page++) {
        for (let col = 0; col < this.width; col++) {
          let byte = 0;
          for (let bit = 0; bit < 8; bit++) {
            const y = page * 8 + bit;
            const pixelIndex = y * this.width + col;

            if (pixelIndex < frameBuffer.length && frameBuffer[pixelIndex] > 0) {
              byte |= (1 << bit);
            }
          }
          bytes.push(byte);
        }
      }

      // Format frame data
      lines.push(`    // Frame ${frameIndex + 1}`);
      lines.push('    {');

      const bytesPerLine = 16;
      for (let i = 0; i < bytes.length; i += bytesPerLine) {
        const chunk = bytes.slice(i, i + bytesPerLine);
        const formatted = chunk.map(b => `0x${b.toString(16).padStart(2, '0')}`).join(', ');
        lines.push(`        ${formatted}${i + bytesPerLine < bytes.length ? ',' : ''}`);
      }

      lines.push(`    }${frameIndex < frames.length - 1 ? ',' : ''}`);
    });

    lines.push('};');

    return lines.join('\n');
  }

  /**
   * Generate animation state management code
   */
  private generateAnimationStateCode(hasFastAnimation: boolean): string {
    const lines: string[] = [];

    lines.push('// Animation state tracking');
    lines.push('static uint32_t anim_timer = 0;');
    lines.push('static uint8_t current_frame = 0;');
    lines.push('static anim_state_t current_state = ANIM_IDLE;');
    lines.push('');
    lines.push('// Get current animation state based on WPM');
    lines.push('static anim_state_t get_animation_state(void) {');
    lines.push('    uint8_t wpm = get_current_wpm();');
    lines.push('    ');
    lines.push('    if (wpm < WPM_IDLE_THRESHOLD) {');
    lines.push('        return ANIM_IDLE;');
    if (hasFastAnimation) {
      lines.push('    } else if (wpm >= WPM_TYPING_THRESHOLD) {');
      lines.push('        return ANIM_FAST;');
    }
    lines.push('    } else {');
    lines.push('        return ANIM_TYPING;');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    lines.push('// Update animation frame');
    lines.push('static void update_animation_frame(void) {');
    lines.push('    anim_state_t new_state = get_animation_state();');
    lines.push('    ');
    lines.push('    // Reset frame if state changed');
    lines.push('    if (new_state != current_state) {');
    lines.push('        current_state = new_state;');
    lines.push('        current_frame = 0;');
    lines.push('        anim_timer = timer_read32();');
    lines.push('        return;');
    lines.push('    }');
    lines.push('    ');
    lines.push('    // Get frame duration for current state');
    lines.push('    uint32_t frame_duration;');
    lines.push('    uint8_t frame_count;');
    lines.push('    ');
    lines.push('    switch (current_state) {');
    lines.push('        case ANIM_IDLE:');
    lines.push('            frame_duration = IDLE_FRAME_DURATION;');
    lines.push('            frame_count = IDLE_FRAME_COUNT;');
    lines.push('            break;');
    lines.push('        case ANIM_TYPING:');
    lines.push('            frame_duration = TYPING_FRAME_DURATION;');
    lines.push('            frame_count = TYPING_FRAME_COUNT;');
    lines.push('            break;');
    if (hasFastAnimation) {
      lines.push('        case ANIM_FAST:');
      lines.push('            frame_duration = FAST_FRAME_DURATION;');
      lines.push('            frame_count = FAST_FRAME_COUNT;');
      lines.push('            break;');
    }
    lines.push('        default:');
    lines.push('            frame_duration = IDLE_FRAME_DURATION;');
    lines.push('            frame_count = IDLE_FRAME_COUNT;');
    lines.push('            break;');
    lines.push('    }');
    lines.push('    ');
    lines.push('    // Advance frame if enough time has passed');
    lines.push('    if (timer_elapsed32(anim_timer) > frame_duration) {');
    lines.push('        anim_timer = timer_read32();');
    lines.push('        current_frame = (current_frame + 1) % frame_count;');
    lines.push('    }');
    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Generate WPM counter display code
   */
  private generateWPMDisplayCode(): string {
    const lines: string[] = [];

    lines.push('// Render WPM counter');
    lines.push('static void render_wpm_counter(void) {');
    lines.push('    uint8_t wpm = get_current_wpm();');
    lines.push('    char wpm_str[16];');
    lines.push('    ');
    lines.push('    oled_set_cursor(0, 0);');
    lines.push('    oled_write_P(PSTR("WPM: "), false);');
    lines.push('    ');
    lines.push('    snprintf(wpm_str, sizeof(wpm_str), "%3d", wpm);');
    lines.push('    oled_write(wpm_str, false);');
    lines.push('    ');
    lines.push('    // Status indicator');
    lines.push('    oled_set_cursor(0, 1);');
    lines.push('    if (wpm < WPM_IDLE_THRESHOLD) {');
    lines.push('        oled_write_P(PSTR("[ Idle ]"), false);');
    lines.push('    } else if (wpm >= WPM_TYPING_THRESHOLD) {');
    lines.push('        oled_write_P(PSTR("[ Fast! ]"), false);');
    lines.push('    } else {');
    lines.push('        oled_write_P(PSTR("[Typing]"), false);');
    lines.push('    }');
    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Generate main render function
   */
  private generateRenderFunction(hasFastAnimation: boolean): string {
    const lines: string[] = [];

    lines.push('// Main render function - call from oled_task_user()');
    lines.push('void render_wpm_animation(bool is_master) {');
    lines.push('    if (is_master) {');
    lines.push('        // Master side: show animation');
    lines.push('        update_animation_frame();');
    lines.push('        ');
    lines.push('        // Render current frame based on state');
    lines.push('        switch (current_state) {');
    lines.push('            case ANIM_IDLE:');
    lines.push('                oled_write_raw_P(idle_animation[current_frame], OLED_SIZE);');
    lines.push('                break;');
    lines.push('            case ANIM_TYPING:');
    lines.push('                oled_write_raw_P(typing_animation[current_frame], OLED_SIZE);');
    lines.push('                break;');
    if (hasFastAnimation) {
      lines.push('            case ANIM_FAST:');
      lines.push('                oled_write_raw_P(fast_animation[current_frame], OLED_SIZE);');
      lines.push('                break;');
    }
    lines.push('        }');
    lines.push('    } else {');
    lines.push('        // Slave side: show WPM counter or other info');
    if (this.config.showCounter) {
      lines.push('        render_wpm_counter();');
    } else {
      lines.push('        // Add your custom display here');
      lines.push('        oled_write_P(PSTR("Corne\\nKeyboard"), false);');
    }
    lines.push('    }');
    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Generate rules.mk additions for WPM support
   */
  generateRulesMk(): string {
    const lines: string[] = [];

    lines.push('# WPM Support');
    lines.push('WPM_ENABLE = yes');
    lines.push('');
    lines.push('# OLED Support');
    lines.push('OLED_ENABLE = yes');
    lines.push('OLED_DRIVER = ssd1306');

    return lines.join('\n');
  }

  /**
   * Generate usage template for keymap.c
   */
  generateKeymapTemplate(): string {
    const lines: string[] = [];

    lines.push('// Add to your keymap.c');
    lines.push('');
    lines.push('#ifdef OLED_ENABLE');
    lines.push('');
    lines.push('bool oled_task_user(void) {');
    lines.push('    // Render WPM animation on primary display');
    lines.push('    render_wpm_animation(is_keyboard_master());');
    lines.push('    return false;');
    lines.push('}');
    lines.push('');
    lines.push('#endif // OLED_ENABLE');

    return lines.join('\n');
  }
}

/**
 * Default WPM configuration
 */
export const DEFAULT_WPM_CONFIG: WPMConfig = {
  enabled: true,
  idleThreshold: 20,
  typingThreshold: 60,
  updateInterval: 100,
  showCounter: true,
  counterPosition: 'top',
};
