// Generated by Corne CLI
// Keyboard: crkbd
// Keymap: miclayout
// Author: corne-cli

#include <stdio.h>
#include "quantum.h"
#include "keymap.h"
#include "action.h"
#include "print.h"
#include "oled.h"

const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  // Layer 0: Base
  [0] = {
    { KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC },
{ KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_NO, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS },
{ MO(1), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, TT(2), KC_ENT }
  },
  // Layer 1: Símbolos
  [1] = {
    { KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MINS, KC_EQL },
{ KC_TAB, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BSLS, KC_SLSH, KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_SCLN, KC_QUOT },
{ KC_ESC, KC_LCTL, KC_LSFT, KC_LALT, KC_LGUI, KC_SPC, KC_SPC, KC_SPC, KC_RGUI, KC_RALT, KC_RSFT, KC_RCTL, KC_DEL, KC_DEL }
  },
  // Layer 2: F-keys/Números
  [2] = {
    { KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_NO },
{ KC_TAB, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC },
{ KC_ESC, KC_LCTL, KC_LSFT, KC_LALT, KC_LGUI, KC_SPC, KC_SPC, KC_SPC, KC_RGUI, KC_RALT, KC_RSFT, KC_RCTL, KC_ENT, KC_NO }
  },
};

const uint16_t PROGMEM fn_actions[] = {
};
