import { KeymapGenerator } from '../../../src/core/keymap/generator';
import type { Keymap, Layer } from '../../../src/types';

describe('KeymapGenerator', () => {
  let generator: KeymapGenerator;

  beforeEach(() => {
    generator = new KeymapGenerator();
  });

  describe('generate', () => {
    it('should generate keymap.c for crkbd with LAYOUT_split_3x6_3', () => {
      const keymap: Keymap = {
        name: 'test',
        author: 'tester',
        layers: [
          {
            name: 'Base',
            keys: [
              ['KC_Q', 'KC_W', 'KC_E', 'KC_R', 'KC_T', 'KC_Y', 'KC_U', 'KC_I', 'KC_O', 'KC_P', 'KC_A', 'KC_S'],
              ['KC_D', 'KC_F', 'KC_G', 'KC_H', 'KC_J', 'KC_K', 'KC_L', 'KC_SCLN', 'KC_QUOT', 'KC_Z', 'KC_X', 'KC_C'],
              ['KC_V', 'KC_B', 'KC_N', 'KC_M', 'KC_COMM', 'KC_DOT', 'KC_SLSH', 'KC_SPC', 'KC_ENT', 'KC_BSPC', 'KC_ESC', 'KC_TAB'],
              ['KC_LGUI', 'KC_LALT', 'KC_SPC', 'KC_ENT', 'KC_RALT', 'KC_RGUI']
            ]
          }
        ]
      };

      const result = generator.generate(keymap, { keyboard: 'crkbd' });

      expect(result).toContain('LAYOUT_split_3x6_3');
      expect(result).toContain('KC_Q');
      expect(result).toContain('KC_Y');
      expect(result).toContain('#include QMK_KEYBOARD_H');
    });

    it('should include comments when includeComments is true', () => {
      const keymap: Keymap = {
        name: 'test',
        layers: [
          {
            name: 'Base',
            keys: [
              ['KC_Q', 'KC_W', 'KC_E', 'KC_R', 'KC_T', 'KC_Y', 'KC_U', 'KC_I', 'KC_O', 'KC_P', 'KC_A', 'KC_S'],
              ['KC_D', 'KC_F', 'KC_G', 'KC_H', 'KC_J', 'KC_K', 'KC_L', 'KC_SCLN', 'KC_QUOT', 'KC_Z', 'KC_X', 'KC_C'],
              ['KC_V', 'KC_B', 'KC_N', 'KC_M', 'KC_COMM', 'KC_DOT', 'KC_SLSH', 'KC_SPC', 'KC_ENT', 'KC_BSPC', 'KC_ESC', 'KC_TAB'],
              ['KC_LGUI', 'KC_LALT', 'KC_SPC', 'KC_ENT', 'KC_RALT', 'KC_RGUI']
            ]
          }
        ]
      };

      const result = generator.generate(keymap, { keyboard: 'crkbd', includeComments: true });

      expect(result).toContain('// Generated by Corne CLI');
      expect(result).toContain('// Layer 0: Base');
    });

    it('should use correct data type for crkbd (uint16_t)', () => {
      const keymap: Keymap = {
        name: 'test',
        layers: [
          {
            name: 'Base',
            keys: [
              ['KC_Q', 'KC_W', 'KC_E', 'KC_R', 'KC_T', 'KC_Y', 'KC_U', 'KC_I', 'KC_O', 'KC_P', 'KC_A', 'KC_S'],
              ['KC_D', 'KC_F', 'KC_G', 'KC_H', 'KC_J', 'KC_K', 'KC_L', 'KC_SCLN', 'KC_QUOT', 'KC_Z', 'KC_X', 'KC_C'],
              ['KC_V', 'KC_B', 'KC_N', 'KC_M', 'KC_COMM', 'KC_DOT', 'KC_SLSH', 'KC_SPC', 'KC_ENT', 'KC_BSPC', 'KC_ESC', 'KC_TAB'],
              ['KC_LGUI', 'KC_LALT', 'KC_SPC', 'KC_ENT', 'KC_RALT', 'KC_RGUI']
            ]
          }
        ]
      };

      const result = generator.generate(keymap, { keyboard: 'crkbd' });

      expect(result).toContain('const uint16_t PROGMEM keymaps');
    });
  });

  describe('normalizeKeycode', () => {
    it('should normalize KC_Y correctly', () => {
      const keymap: Keymap = {
        name: 'test',
        layers: [
          {
            name: 'Base',
            keys: [
              ['KC_Q', 'KC_W', 'KC_E', 'KC_R', 'KC_T', 'KC_Y', 'KC_U', 'KC_I', 'KC_O', 'KC_P', 'KC_A', 'KC_S'],
              ['KC_D', 'KC_F', 'KC_G', 'KC_H', 'KC_J', 'KC_K', 'KC_L', 'KC_SCLN', 'KC_QUOT', 'KC_Z', 'KC_X', 'KC_C'],
              ['KC_V', 'KC_B', 'KC_N', 'KC_M', 'KC_COMM', 'KC_DOT', 'KC_SLSH', 'KC_SPC', 'KC_ENT', 'KC_BSPC', 'KC_ESC', 'KC_TAB'],
              ['KC_LGUI', 'KC_LALT', 'KC_SPC', 'KC_ENT', 'KC_RALT', 'KC_RGUI']
            ]
          }
        ]
      };

      const result = generator.generate(keymap, { keyboard: 'crkbd' });

      expect(result).toContain('KC_Y');
      expect(result).not.toContain('KC_T, KC_Y, KC_U');
    });

    it('should handle layer switching keys (MO, TT, TG)', () => {
      const keymap: Keymap = {
        name: 'test',
        layers: [
          {
            name: 'Base',
            keys: [
              ['KC_Q', 'KC_W', 'KC_E', 'KC_R', 'KC_T', 'KC_Y', 'KC_U', 'KC_I', 'KC_O', 'KC_P', 'KC_A', 'KC_S'],
              ['MO(1)', 'KC_D', 'KC_F', 'KC_G', 'KC_H', 'KC_J', 'KC_K', 'KC_L', 'KC_SCLN', 'KC_QUOT', 'KC_Z', 'KC_X'],
              ['KC_V', 'KC_B', 'KC_N', 'KC_M', 'KC_COMM', 'KC_DOT', 'KC_SLSH', 'KC_SPC', 'KC_ENT', 'KC_BSPC', 'KC_ESC', 'KC_TAB'],
              ['KC_LGUI', 'TT(2)', 'KC_SPC', 'KC_ENT', 'MO(2)', 'KC_RGUI']
            ]
          }
        ]
      };

      const result = generator.generate(keymap, { keyboard: 'crkbd' });

      expect(result).toContain('MO(1)');
      expect(result).toContain('TT(2)');
      expect(result).toContain('MO(2)');
    });

    it('should convert KC_TRNS to KC_TRNS', () => {
      const keymap: Keymap = {
        name: 'test',
        layers: [
          {
            name: 'Base',
            keys: [
              ['KC_Q', 'KC_W', 'KC_E', 'KC_R', 'KC_T', 'KC_Y', 'KC_U', 'KC_I', 'KC_O', 'KC_P', 'KC_A', 'KC_S'],
              ['KC_D', 'KC_F', 'KC_G', 'KC_H', 'KC_J', 'KC_K', 'KC_L', 'KC_SCLN', 'KC_QUOT', 'KC_Z', 'KC_X', 'KC_C'],
              ['KC_V', 'KC_B', 'KC_N', 'KC_M', 'KC_TRNS', 'KC_TRNS', 'KC_SLSH', 'KC_SPC', 'KC_ENT', 'KC_BSPC', 'KC_ESC', 'KC_TAB'],
              ['KC_LGUI', 'KC_LALT', 'KC_SPC', 'KC_ENT', 'KC_RALT', 'KC_RGUI']
            ]
          }
        ]
      };

      const result = generator.generate(keymap, { keyboard: 'crkbd' });

      expect(result).toContain('KC_TRNS');
    });
  });
});